from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Any, Protocol

from agent_sdlc.agents.roles import Role
from agent_sdlc.types import AgentResult, CommandResult, Decision, PrComment, WorkItem


class AgentRunner(Protocol):
    async def run(self, role: Role, prompt: str, cwd: Path, max_turns: int,
                  trace: Path | None = None,
                  token_budget: int | None = None) -> AgentResult: ...


class DeciderPort(Protocol):
    def decide(self, gate: str, state: dict[str, Any]) -> dict[str, Decision]: ...


class WorkspacePort(Protocol):
    def worktree_path(self, item_id: int) -> Path: ...
    def create(self, item_id: int, branch: str) -> Path: ...
    def reset(self, wt: Path) -> None: ...
    def install(self, wt: Path, log: Path | None = None) -> CommandResult: ...
    def run_checks(self, wt: Path,
                   log_for: Callable[[str], Path | None] | None = None
                   ) -> list[CommandResult]: ...
    def commit(self, wt: Path, message: str) -> bool: ...
    def changed_files(self, wt: Path) -> list[str]: ...
    def diff_lines(self, wt: Path) -> int: ...
    def diff(self, wt: Path, max_chars: int = 60000,
             paths: list[str] | None = None, stat: bool = False) -> str: ...
    def blob_digest(self, wt: Path, paths: list[str]) -> str: ...
    def tracked_files(self, wt: Path) -> list[str]: ...
    def remove(self, item_id: int, branch: str) -> None: ...


class AdoPort(Protocol):
    def list_intake(self) -> list[WorkItem]: ...
    def list_closed(self, limit: int) -> list[WorkItem]: ...
    def get_work_item(self, id: int) -> WorkItem: ...
    def comment_work_item(self, id: int, html_text: str) -> None: ...
    def set_tag(self, id: int, tag: str, present: bool) -> None: ...
    def has_tag(self, id: int, tag: str) -> bool: ...
    def push_branch(self, worktree: Path, branch: str) -> None: ...
    def create_pr(self, branch: str, title: str, body: str, work_item_id: int) -> int: ...
    def update_pr(self, pr_id: int, body: str) -> None: ...
    def pr_status(self, pr_id: int) -> str: ...
    def pr_comments(self, pr_id: int) -> list[PrComment]: ...
    def reply_pr(self, pr_id: int, thread_id: int, parent_comment_id: int, text: str) -> None: ...
    def comment_pr(self, pr_id: int, text: str) -> None: ...
    def delete_branch(self, branch: str) -> None: ...
